### ISSUE TITLE
마이페이지 알림 설정

### ISSUE THREAD

**Issue by thalals** [THT-Team/THT-Server#103]
## 📚 To-do

- [ ] 마케팅정보 수신동의를 해제 -> 모든 이벤트성 알림 해제
- [ ] 새로운 매치, 나를 좋아요, 새로운 대화, 기존 대화
- [ ] 회원가입시 해당 테이블 생성  

---
## 🙏 To-Reviewer
-
