### ISSUE TITLE
계정 탈퇴

### ISSUE THREAD

**Issue by thalals** [THT-Team/THT-Server#104]
## 📚 To-do

- [x] 탈퇴 →계정 비활성화 1년? 90일? 기간 정해야할듯?!
- [x] 탈퇴 사유 기록
- [x] 피드백 기록 (필수 요청)
- [ ] 로그인, 회원가입시 계정 복구기간 체크

---
## 🙏 To-Reviewer
-
