### ISSUE TITLE
메인화면 매칭할 유저 리스트 조회 리팩토링

### ISSUE THREAD

**Issue by thalals** [THT-Team/THT-Server#140]
## 📚 To-do

- [x] 기존 메인화면 조회 문서 삭제
- [x] 같은 데일리 토픽 주제를 선택한 유저만 표출
- [x] 유저의 선호성별 유저만 표출
- [x] 이미 해당 주제어에서 좋아요한 사람은 제외
- [x] 어딘가에서 싫어요한 유저는 7일동안 표출 제외
- [x] 아무런 액션없이 지나간 사람은 마지막에 다시 조회 → last 여부를 response 에 응답 후 클라이언트에게 처음부터 cursor 를 조회해달라고 요청

---
## 🙏 To-Reviewer
-
